# Generated by Django 5.2.4 on 2025-09-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bg_color',
            field=models.CharField(default='#f5f5f5', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='blur_bg',
            field=models.BooleanField(default=False),
        ),
    ]
