# Generated by Django 5.2.4 on 2025-08-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='layout',
            field=models.CharField(choices=[('layout1', 'Layout 1 - Image left, text right'), ('layout2', 'Layout 2 - Text over image'), ('layout3', 'Layout 3 - Image grid')], default='layout1', max_length=20),
        ),
    ]
