# Generated by Django 5.2.4 on 2025-10-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_drop_in_event_max_attendees_eventbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='num_guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
