# Generated by Django 5.2.4 on 2025-09-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_end_datetime_alter_event_start_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artist_intro',
        ),
        migrations.RemoveField(
            model_name='event',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='artist_portrait',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
