# Generated by Django 5.2.4 on 2025-11-04 10:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventbooking_num_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='Full_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bg_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='blur_bg',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_current_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(default='v1762250378', max_length=255, verbose_name='event_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='potrait_image',
            field=cloudinary.models.CloudinaryField(default='v1762250378', max_length=255, verbose_name='potrait_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(default='short discription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventimage',
            name='art_id',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='price',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventimage',
            name='title',
            field=models.CharField(default='Tittle', max_length=255),
            preserve_default=False,
        ),
    ]
