# Generated by Django 5.2.4 on 2025-09-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_artist_intro_remove_event_artist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='layout',
        ),
    ]
