# Generated by Django 5.2.4 on 2025-11-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_gallery_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
