# Generated by Django 5.2.4 on 2025-09-29 15:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/bg/'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
