# Generated by Django 5.2.4 on 2025-09-29 15:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_bg_image_alter_eventimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bg_image',
        ),
        migrations.AddField(
            model_name='eventimage',
            name='bg_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='bg_image'),
        ),
    ]
