# Generated by Django 5.2.4 on 2025-11-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_is_gallery_event_eventimage_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Full_description',
            new_name='full_description',
        ),
    ]
