services:
  - type: web
    name: gallery-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py crontab add
    startCommand: gunicorn GalleriVretinger.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.9

databases:
  - name: postgres
    plan: free
