# Generated by Django 5.2.4 on 2025-10-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='approved',
            new_name='is_confirmed',
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
