# Generated by Django 5.2.4 on 2025-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
