# Generated by Django 5.2.4 on 2025-10-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_final_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contract_signature',
            field=models.ImageField(blank=True, null=True, upload_to='contracts/signatures/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='contract_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='signed_contract_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/signed_pdfs/'),
        ),
    ]
