# Generated by Django 5.2.4 on 2025-11-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_contract_signature_booking_contract_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='signed_contract_pdf',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
